# 代理服务器配置(为了测试方便这里暂时把服务器配置写在客户端配置里)
# 已授权客户端key
clients:
  - kas19kn#fkhDKAsadhk
  - KAHSKKASdhkajsk211a
  - jas#HFKfkkhakkdajdL

# 指定代理服务器host&port
server-host: 127.0.0.1
server-port: 11111

# 本地服务器host
local-host: 127.0.0.1

# 代理客户端认证密钥client-key
client-key: kas19kn#fkhDKAsadhk

# server-port与local-port映射配置
config:
  # server-port：代理服务器外部访问端口
  # client-port：代理客户端实际使用端口
  # proxy-type： 采用的代理模式
  # description：代理描述
  #
  #
  # http代理
  # 这里也直接转发tcp流量，速度会较快
  - server-port: 9980
    client-port: 80
    proxy-type: tcp
    description: http代理